<script lang="ts" setup>
import type { Header, Item } from "vue3-easy-data-table";
definePageMeta({
  layout: "dashboard",
});

const headers: Header[] = [
  { text: "Amount of clicks", value: "player" },
  { text: "Affiliate name", value: "team" },
  { text: "Time", value: "number" },
  { text: "Conversion funnel", value: "position", sortable: true },
];

const items: Item[] = [
  {
    player: "Stephen Curry",
    team: "GSW",
    number: 30,
    position: "G",
  },
  {
    player: "Lebron James",
    team: "LAL",
    number: 6,
    position: "F",
  },
  {
    player: "Kevin Durant",
    team: "BKN",
    number: 7,
    position: "F",
  },
  {
    player: "Giannis Antetokounmpo",
    team: "MIL",
    number: 34,
    position: "F",
  },
];
</script>

<template>
  <div>
    <div>
      <DashboardTitle :title="'Overview'" :isRow="false" />
      <div class="flex justify-start gap-2 pt-2">
        <div class="card_container">
          <p class="numbers">58</p>
          <p class="title">Number of affiliates</p>
        </div>
        <div class="card_container">
          <p class="numbers">21</p>
          <p class="title">Number of active affiliates</p>
        </div>
        <div class="card_container">
          <p class="numbers">6854</p>
          <p class="title">Number of Clicks</p>
        </div>

        <div class="card_container">
          <p class="numbers">2128</p>
          <p class="title">Number of Conversions</p>
        </div>

        <div class="card_container">
          <p class="numbers">52,856 $</p>
          <p class="title">Total sales amount</p>
        </div>
        <div class="card_container">
          <p class="numbers">52,925,254</p>
          <p class="title">Total commission earned</p>
        </div>
      </div>

      <div class="flex justify-start gap-2 pt-6 pb-11">
        <div class="card_container">
          <p class="numbers">12 %</p>
          <p class="title">Converssion rate</p>
        </div>
        <div class="card_container">
          <p class="numbers">21,256 $</p>
          <p class="title">Revenue generated by all affiliates</p>
        </div>
        <div class="card_container">
          <p class="numbers">524</p>
          <p class="title">Total number of commissions request</p>
        </div>

        <div class="card_container">
          <p class="numbers">52</p>
          <p class="title">Total number of approved commision</p>
        </div>

        <div class="card_container">
          <p class="numbers">115</p>
          <p class="title">Total number of rejected commissions</p>
        </div>
        <div class="card_container">
          <p class="numbers">14,984</p>
          <p class="title">Total amount of comissions paid outrrr</p>
        </div>
      </div>
    </div>
    <div>
      <DashboardTitle :title="'Clicks'" :isRow="false" />
      <div class="w-full max-w-full pb-10">
        <Table :headers="headers" :items="items" />
      </div>
    </div>
  </div>
</template>

<style>
.numbers {
  @apply text-center pt-4 text-dashboard-font-color font-bold text-lg font-montse;
}

.title {
  @apply text-center pt-1 pb-3 text-[#FF6137] font-medium text-xs font-montse px-[10px];
}

.card_container {
  @apply rounded-md bg-white w-[168px] h-[93px] border-solid border-[1px] border-[#E4E4E7];
}

.vue3-easy-data-table__header th .header.direction-left {
  justify-content: center !important;
}
.vue3-easy-data-table__body td.direction-left {
  text-align: center !important;
}

.header-text {
  color: #93a3b0cc;
  font-size: 12px;
  font-weight: 400;
  @apply font-montse;
}

.vue3-easy-data-table[data-v-19cc4b1b] {
  border-radius: 8px;
  border: 1px solid #e4e4e7;
}

.vue3-easy-data-table__header tr {
  height: 88px !important;
}
.vue3-easy-data-table__body tr {
  height: 40px;
}
</style>
