<script setup>
definePageMeta({
  layout: "dashboard",
});
</script>

<template>
  <div>
    <div>
      <DashboardTitle :title="'Overview'" :isRow="false" />
      <div class="flex justify-start gap-2 pt-2">
        <div
          class="card_container"
        >
          <p class="numbers">58</p>
          <p class="title">
            Number of affiliates
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">21</p>
          <p class="title">
            Number of active affiliates
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">6854</p>
          <p class="title">
            Number of Clicks
          </p>
        </div>

        <div
          class="card_container"
        >
          <p class="numbers">2128</p>
          <p class="title">
            Number of Conversions
          </p>
        </div>

        <div
          class="card_container"
        >
          <p class="numbers">
            52,856 $
          </p>
          <p class="title">
            Total sales amount
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">
            52,925,254
          </p>
          <p class="title">
            Total commission earned
          </p>
        </div>
      </div>

      <!-- ////////// -->

      <div class="flex justify-start gap-2 pt-6 pb-11">
        <div
          class="card_container"
        >
          <p class="numbers">12 %</p>
          <p class="title">
            Converssion rate
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">
            21,256 $
          </p>
          <p class="title">
            Revenue generated by all affiliates
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">524</p>
          <p class="title">
            Total number of commissions request
          </p>
        </div>

        <div
          class="card_container"
        >
          <p class="numbers">52</p>
          <p class="title">
            Total number of approved commision
          </p>
        </div>

        <div
          class="card_container"
        >
          <p class="numbers">115</p>
          <p class="title">
            Total number of rejected commissions
          </p>
        </div>
        <div
          class="card_container"
        >
          <p class="numbers">
            14,984
          </p>
          <p class="title">
            Total amount of comissions paid out
          </p>
        </div>
      </div>
    </div>
    <div>
      <DashboardTitle :title="'Clicks'" :isRow="false" />
    </div>
  </div>
</template>

<style scoped>
.numbers{
   @apply text-center pt-4 text-dashboard-font-color font-bold text-lg font-montse
}

.title{
   @apply text-center pt-1 pb-3 text-[#FF6137] font-medium text-xs font-montse px-[10px]
}

.card_container{
   @apply rounded-md bg-white w-[168px] h-[93px] border-solid border-[1px] border-[#E4E4E7]
}
</style>
